name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                type: string

permissions:
    contents: write

jobs:
    build-mac:
        runs-on: macos-latest
        strategy:
            matrix:
                node-version: ['21.x']
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '21.x'

            - name: Install NPM Dependencies
              run: npm install

            - name: Cleanup Mounted Volumes
              run: |
                  MOUNTED=$(hdiutil info | grep "/Volumes/TweakPHP-Installer" | awk '{print $1}')
                  if [ -n "$MOUNTED" ]; then
                      hdiutil detach "$MOUNTED" || true
                  fi

            - name: Make
              run: npm run publish -- --arch="universal"
              env:
                  VITE_LSP_WEBSOCKET_PORT: 54331
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
