name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                type: string

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.event.inputs.version }}
                  release_name: ${{ github.event.inputs.version }}
                  body: 'Automated Release'
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-mac:
        needs: release
        runs-on: macos-latest
        strategy:
            matrix:
                node-version: ['21.x']
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '21.x'

            - name: Install NPM Dependencies
              run: npm install

            - name: Cleanup Mounted Volumes
              run: |
                  MOUNTED=$(hdiutil info | grep "/Volumes/TweakPHP-Installer" | awk '{print $1}')
                  if [ -n "$MOUNTED" ]; then
                      hdiutil detach "$MOUNTED" || true
                  fi

            - name: Make
              run: npm run make --platform=darwin --arch=universal
              env:
                  VITE_LSP_WEBSOCKET_PORT: 54331

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ needs.release.outputs.upload_url }}
                  asset_path: ./out/make/TweakPHP-Installer.dmg
                  asset_name: TweakPHP-Installer.dmg
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
