name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                type: string

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set version on package.json
              run: node set-version.js ${{ github.event.inputs.version }}

            - name: Commit version change
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'Update version to ${{ github.event.inputs.version }}'

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.event.inputs.version }}
                  release_name: ${{ github.event.inputs.version }}
                  body: 'Automated Release'
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-mac:
        needs: release
        runs-on: macos-latest
        strategy:
            matrix:
                node-version: ['21.x']
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '21.x'

            - name: Install NPM Dependencies
              run: npm install

            - name: Cleanup Mounted Volumes
              run: |
                  MOUNTED=$(hdiutil info | grep "/Volumes/TweakPHP-Installer" | awk '{print $1}')
                  if [ -n "$MOUNTED" ]; then
                      hdiutil detach "$MOUNTED" || true
                  fi

            - name: Make
              run: npm run make --platform=darwin --arch=arm64
              env:
                  VITE_LSP_WEBSOCKET_PORT: 54331

            - name: List Files in the darwin directory
              run: ls -la ./out/make/zip/darwin

            - name: List Files in the darwin arm64 directory
              run: ls -la ./out/make/zip/darwin/arm64

            - name: Run xattr on the app
              run: |
                  cd ./out/TweakPHP-darwin-arm64
                  xattr -cr TweakPHP.app

            - name: Create Zip without output
              run: |
                  cd ./out/TweakPHP-darwin-arm64
                  zip -r -X ../TweakPHP-${{ github.event.inputs.version }}.zip TweakPHP.app

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ needs.release.outputs.upload_url }}
                  asset_path: ./out/TweakPHP-${{ github.event.inputs.version }}.zip
                  asset_name: TweakPHP-${{ github.event.inputs.version }}.zip
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
